# Once the environment is installed, activate it and run:
# python -m ipykernel install --user --name=machine-learning
# This should make the environment available from Jupyter
# Notebooks
name: machine-learning

dependencies:
  - python=3.7
  - keras=2.3
  - matplotlib=3.3
  - tensorflow=2.0
  - tensorflow-gpu=2.0
  - ipykernel=5.3
  - scikit-learn=0.23.2
  - pandas=1.1.3
  - pip=20.2
  - pip:
    - tensorflow==2.3
